# Generated by Django 5.1.6 on 2025-03-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Remedy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dname", models.CharField(max_length=100)),
                ("dtype", models.CharField(max_length=100)),
                ("dcause", models.CharField(max_length=200)),
                ("dremedy", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "remedy",
            },
        ),
    ]
