# Generated by Django 5.1.6 on 2025-03-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="remedy",
            table="comedy",
        ),
    ]
