# Generated by Django 5.1.6 on 2025-03-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0002_alter_remedy_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="remedy",
            table="remedy",
        ),
    ]
