# Generated by Django 5.0.4 on 2025-03-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_alter_remedy_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('upass', models.CharField(default='', max_length=25)),
                ('uemail', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
